/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.vlasnik;

import kontroler.Kontroler;
import domain.Klijent;
import domain.NamenaNekretnine;
import domain.Nekretnina;
import domain.NekretninaZaIzdavanje;
import domain.NekretninaZaProdaju;
import domain.OpstaDomenskaKlasa;
import domain.UgovorOKupoprodajiNekretnine;
import domain.UgovorOZakupuNekretnine;
import domain.Vlasnik;
import form.FrmDialog;
import form.FrmForma;
import form.IPanel;
import form.PanelModeEnum;
import form.klijent.PnlUnosKlijenta;
import form.nekretnina.PnlNovaNekretnina;
import form.nekretnina.model.TableModelNekretnina;
import form.ugovorProdaja.model.TableModelUgovoriOKupoprodaji;
import form.ugovorZakup.model.TableModelUgovoriOIzdavanju;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class PnlPrikazVlasnika extends javax.swing.JPanel implements IPanel {
    
    PnlUnosVlasnika vlasnik;

    /**
     * Creates new form PnlPrikazVlasnika
     */
    public PnlPrikazVlasnika() {
        initComponents();
        dekorisiPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVlasnik = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljivanje = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPrikaziZaIznajmljivanje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdaja = new javax.swing.JTable();
        btnPrikaziZaProdaju = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        pnlVlasnik.setLayout(new javax.swing.BoxLayout(pnlVlasnik, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Nekretnine koje vlasnik nudi za iznajmljivanje:");

        tblIznajmljivanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljivanje);

        jLabel2.setText("Nekretnine koje vlasnik nudi za prodaju:");

        btnPrikaziZaIznajmljivanje.setText("Prikazi detalje");
        btnPrikaziZaIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziZaIznajmljivanjeActionPerformed(evt);
            }
        });

        tblProdaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProdaja);

        btnPrikaziZaProdaju.setText("Prikazi detalje");
        btnPrikaziZaProdaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziZaProdajuActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVlasnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrikaziZaIznajmljivanje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrikaziZaProdaju, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOtkazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrikaziZaIznajmljivanje)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrikaziZaProdaju)
                .addGap(18, 18, 18)
                .addComponent(btnOtkazi)
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziZaIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziZaIznajmljivanjeActionPerformed
        TableModelNekretnina model = (TableModelNekretnina) tblIznajmljivanje.getModel();
        int row = tblIznajmljivanje.getSelectedRow();
        if (row != -1) {
            Nekretnina nekretnina = model.getNekretnine().get(row);
            PnlNovaNekretnina panel = new PnlNovaNekretnina(PanelModeEnum.PRIKAZ, true);
            panel.popuniPolja(nekretnina);
            FrmDialog form = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true,panel);
            form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati nekretninu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziZaIznajmljivanjeActionPerformed

    private void btnPrikaziZaProdajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziZaProdajuActionPerformed
        TableModelNekretnina model = (TableModelNekretnina) tblProdaja.getModel();
        int row = tblProdaja.getSelectedRow();
        if (row != -1) {
            Nekretnina nekretnina = model.getNekretnine().get(row);
            PnlNovaNekretnina panel = new PnlNovaNekretnina(PanelModeEnum.PRIKAZ, false);
            panel.popuniPolja(nekretnina);
            FrmDialog form = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true,panel);
            form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati nekretninu", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziZaProdajuActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();

    }//GEN-LAST:event_btnOtkaziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPrikaziZaIznajmljivanje;
    private javax.swing.JButton btnPrikaziZaProdaju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlVlasnik;
    private javax.swing.JTable tblIznajmljivanje;
    private javax.swing.JTable tblProdaja;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        vlasnik.popuniPolja(odk);
        Nekretnina nekProdaja = new NekretninaZaProdaju();
        Nekretnina nekIzdavanje = new NekretninaZaIzdavanje();
        try {
            nekProdaja.setVlasnik((Vlasnik) vlasnik.preuzmiPolja());
            nekIzdavanje.setVlasnik((Vlasnik) vlasnik.preuzmiPolja());
            List<Nekretnina> prodaja = Kontroler.getInstance().pretraziNekretnine(nekProdaja);
            List<Nekretnina> zakup = Kontroler.getInstance().pretraziNekretnine(nekIzdavanje);
            TableModelNekretnina modelI = (TableModelNekretnina) tblIznajmljivanje.getModel();
            TableModelNekretnina modelP = (TableModelNekretnina) tblProdaja.getModel();
            modelI.setNekretnine(zakup);
            modelP.setNekretnine(prodaja);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public OpstaDomenskaKlasa preuzmiPolja() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void isprazniPolja() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void dekorisiPanel() {
        Box boxes[] = new Box[1];
        boxes[0] = Box.createHorizontalBox();
        
        boxes[0].createGlue();
        
        pnlVlasnik.add(boxes[0]);
        
        vlasnik = new PnlUnosVlasnika(PanelModeEnum.PRIKAZ);
        vlasnik.postaviVidljivostPoljima(false);
        
        vlasnik.setPreferredSize(new Dimension(400, 220));
        
        boxes[0].add(vlasnik);
        
        TableModelNekretnina izdavanje = new TableModelNekretnina(new LinkedList<>(), NamenaNekretnine.ZA_IZDAVANJE);
        tblIznajmljivanje.setModel(izdavanje);
        TableModelNekretnina prodaja = new TableModelNekretnina(new LinkedList<>(), NamenaNekretnine.ZA_PRODAJU);
        tblProdaja.setModel(prodaja);
    }
    
    @Override
    public void postaviVidljivostPoljima(boolean signal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void popuniPodatke() {
    }
}
