package form.ugovorZakup;

import kontroler.Kontroler;
import domain.Klijent;
import domain.NekretninaZaIzdavanje;
import domain.OpstaDomenskaKlasa;
import domain.UgovorOZakupuNekretnine;
import form.FrmDialog;
import form.IPanel;
import form.PanelModeEnum;
import form.klijent.PnlPretragaKlijenta;
import form.klijent.PnlUnosKlijenta;
import form.nekretnina.PnlNovaNekretnina;
import form.nekretnina.PnlPretragaNekretnine;
import java.awt.Dimension;
import java.awt.Frame;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import sesija.Sesija;
import sun.net.www.content.image.png;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class PnlNoviUgovorOIzdavanjuNekretnine extends javax.swing.JPanel implements IPanel {

    PnlUnosKlijenta klijent;
    PnlNovaNekretnina nekretnina;
    PanelModeEnum mode;

    /**
     * Creates new form PnlNoviUgovorOIzdavanjuNekretnine
     */
    public PnlNoviUgovorOIzdavanjuNekretnine(PanelModeEnum mode) {
        initComponents();
        this.mode = mode;
        dekorisiPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDUgovora = new javax.swing.JTextField();
        cmbDatumSklapanja = new datechooser.beans.DateChooserCombo();
        txtMestoSklapanja = new javax.swing.JTextField();
        cmbDatumOd = new datechooser.beans.DateChooserCombo();
        cmbDatumDo = new datechooser.beans.DateChooserCombo();
        txtUkupnoZaUplatu = new javax.swing.JTextField();
        btnPretraziKlijente = new javax.swing.JButton();
        btnPretraziNekretnine = new javax.swing.JButton();
        btnNoviUnos = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBrojMeseci = new javax.swing.JTextField();
        pnlAgent = new javax.swing.JPanel();
        lblAgent = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        pnlKlijentiINekretnine = new javax.swing.JPanel();

        jLabel1.setText("ID Ugovora:");

        jLabel2.setText("Datum sklapanja:");

        jLabel3.setText("Mesto sklapanja:");

        jLabel4.setText("Datum od:");

        jLabel5.setText("Datum do:");

        jLabel6.setText("Ukupno za uplatu:");

        txtIDUgovora.setEditable(false);

        cmbDatumSklapanja.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    cmbDatumSklapanja.setLocale(new java.util.Locale("sr", "BA", ""));

    cmbDatumOd.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
cmbDatumOd.setLocale(new java.util.Locale("sr", "BA", ""));

cmbDatumDo.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
    new datechooser.view.appearance.ViewAppearance("custom",
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            true,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(0, 0, 255),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.ButtonPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(128, 128, 128),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(0, 0, 255),
            false,
            true,
            new datechooser.view.appearance.swing.LabelPainter()),
        new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
            new java.awt.Color(0, 0, 0),
            new java.awt.Color(255, 0, 0),
            false,
            false,
            new datechooser.view.appearance.swing.ButtonPainter()),
        (datechooser.view.BackRenderer)null,
        false,
        true)));
cmbDatumDo.setLocale(new java.util.Locale("sr", "BA", ""));
cmbDatumDo.setMinDate(cmbDatumOd.getSelectedDate());

txtUkupnoZaUplatu.setEditable(false);
txtUkupnoZaUplatu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

btnPretraziKlijente.setText("Pretrazi klijente");
btnPretraziKlijente.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnPretraziKlijenteActionPerformed(evt);
    }
    });

    btnPretraziNekretnine.setText("Pretrazi nekretnine");
    btnPretraziNekretnine.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnPretraziNekretnineActionPerformed(evt);
        }
    });

    btnNoviUnos.setText("Novi unos");
    btnNoviUnos.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNoviUnosActionPerformed(evt);
        }
    });

    btnSacuvaj.setText("Sacuvaj");
    btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSacuvajActionPerformed(evt);
        }
    });

    btnOtkazi.setText("Otkazi");
    btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOtkaziActionPerformed(evt);
        }
    });

    jLabel7.setText("Broj meseci:");

    txtBrojMeseci.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtBrojMeseciKeyReleased(evt);
        }
    });

    lblAgent.setText("Prijavljeni agent:");

    javax.swing.GroupLayout pnlAgentLayout = new javax.swing.GroupLayout(pnlAgent);
    pnlAgent.setLayout(pnlAgentLayout);
    pnlAgentLayout.setHorizontalGroup(
        pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlAgentLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblAgent)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlAgentLayout.setVerticalGroup(
        pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlAgentLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblAgent)
                .addComponent(lblAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel5)
                .addComponent(jLabel4)
                .addComponent(jLabel6))
            .addGap(27, 27, 27)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbDatumOd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(txtMestoSklapanja, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbDatumSklapanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIDUgovora, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbDatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBrojMeseci, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPretraziKlijente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretraziNekretnine, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(pnlAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(txtUkupnoZaUplatu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                    .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnNoviUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtIDUgovora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(cmbDatumSklapanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtMestoSklapanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(pnlAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtBrojMeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnPretraziKlijente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPretraziNekretnine)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(cmbDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtUkupnoZaUplatu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(btnNoviUnos)
                .addComponent(btnSacuvaj)
                .addComponent(btnOtkazi))
            .addContainerGap(15, Short.MAX_VALUE))
    );

    pnlKlijentiINekretnine.setLayout(new javax.swing.BoxLayout(pnlKlijentiINekretnine, javax.swing.BoxLayout.Y_AXIS));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addComponent(pnlKlijentiINekretnine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlKlijentiINekretnine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 8, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnPretraziKlijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziKlijenteActionPerformed
        PnlPretragaKlijenta panel = new PnlPretragaKlijenta(PanelModeEnum.PRETRAGA);
        FrmDialog pretragaKlijenata = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);

        pretragaKlijenata.setVisible(true);
    }//GEN-LAST:event_btnPretraziKlijenteActionPerformed

    private void btnPretraziNekretnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziNekretnineActionPerformed
        PnlPretragaNekretnine pnlPretragaNek = new PnlPretragaNekretnine(PanelModeEnum.PRETRAGA, true);
        FrmDialog pretragaNek = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, pnlPretragaNek);

        pretragaNek.setVisible(true);
    }//GEN-LAST:event_btnPretraziNekretnineActionPerformed

    private void btnNoviUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviUnosActionPerformed
        isprazniPolja();
        klijent.isprazniPolja();
        nekretnina.isprazniPolja();
        postaviVidljivostPoljima(true);
    }//GEN-LAST:event_btnNoviUnosActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            UgovorOZakupuNekretnine ugovor = (UgovorOZakupuNekretnine) preuzmiPolja();
            ugovor = Kontroler.getInstance().unesiUgovorOZakupu(ugovor);

            popuniPolja(ugovor);
            postaviVidljivostPoljima(false);

            JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali ugovor o izdavanju nekretnine");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtBrojMeseciKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrojMeseciKeyReleased
        Date datumOd = cmbDatumOd.getSelectedDate().getTime();
        Calendar c = Calendar.getInstance();
        c.setTime(datumOd);
        System.out.println("Datum OD: " + datumOd);
        if (!txtBrojMeseci.getText().trim().equals("")) {
            int brojMeseci = Integer.parseInt(txtBrojMeseci.getText().trim());
            c.add(Calendar.MONTH, brojMeseci);
            cmbDatumDo.setEnabled(true);
            cmbDatumDo.setSelectedDate(c);

            System.out.println("Datum DO: " + cmbDatumDo.getSelectedDate().getTime());
            cmbDatumDo.setEnabled(false);

            double kirija;
            try {
                kirija = nekretnina.vratiCenu();
                txtUkupnoZaUplatu.setText(kirija * brojMeseci + "");

            } catch (Exception ex) {
                txtUkupnoZaUplatu.setText("");

            }
        } else {
            txtUkupnoZaUplatu.setText("");
        }
    }//GEN-LAST:event_txtBrojMeseciKeyReleased

    @Override
    public void dekorisiPanel() {
        Box boxes[] = new Box[2];
        boxes[0] = Box.createHorizontalBox();
        boxes[1] = Box.createHorizontalBox();

        boxes[0].createGlue();
        boxes[1].createGlue();

        pnlKlijentiINekretnine.add(boxes[0]);
        pnlKlijentiINekretnine.add(boxes[1]);

        klijent = new PnlUnosKlijenta(PanelModeEnum.PRIKAZ);
        nekretnina = new PnlNovaNekretnina(PanelModeEnum.PRIKAZ, true);

        klijent.setPreferredSize(new Dimension(850, 190));
        nekretnina.setPreferredSize(new Dimension(850, 350));

        boxes[0].add(klijent);
        boxes[1].add(nekretnina);

        cmbDatumDo.setEnabled(false);
        lblAgentName.setText(Sesija.getInstance().getPrijavljeniAgent().toString());

        if (mode == PanelModeEnum.PRIKAZ) {
            btnNoviUnos.setVisible(false);
            btnPretraziKlijente.setVisible(false);
            btnPretraziNekretnine.setVisible(false);
            btnSacuvaj.setVisible(false);
        } else {
            klijent.setVisible(false);
            nekretnina.setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoviUnos;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPretraziKlijente;
    private javax.swing.JButton btnPretraziNekretnine;
    private javax.swing.JButton btnSacuvaj;
    private datechooser.beans.DateChooserCombo cmbDatumDo;
    private datechooser.beans.DateChooserCombo cmbDatumOd;
    private datechooser.beans.DateChooserCombo cmbDatumSklapanja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JPanel pnlAgent;
    private javax.swing.JPanel pnlKlijentiINekretnine;
    private javax.swing.JTextField txtBrojMeseci;
    private javax.swing.JTextField txtIDUgovora;
    private javax.swing.JTextField txtMestoSklapanja;
    private javax.swing.JTextField txtUkupnoZaUplatu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        if (odk instanceof NekretninaZaIzdavanje) {
            nekretnina.popuniPolja(odk);
            nekretnina.setVisible(true);
            SwingUtilities.getWindowAncestor(this).pack();
            SwingUtilities.getWindowAncestor(this).setLocationRelativeTo(null);
            if (!txtBrojMeseci.getText().trim().equals("")) {
                double kirija;
                try {
                    kirija = nekretnina.vratiCenu();
                    txtUkupnoZaUplatu.setText(kirija * Integer.parseInt(txtBrojMeseci.getText().trim()) + "");
                } catch (Exception ex) {
                }
            }
        } else if (odk instanceof Klijent) {
            klijent.popuniPolja(odk);
            klijent.setVisible(true);
            SwingUtilities.getWindowAncestor(this).pack();
            SwingUtilities.getWindowAncestor(this).setLocationRelativeTo(null);
        } else if (odk instanceof UgovorOZakupuNekretnine) {
            UgovorOZakupuNekretnine ugovor = (UgovorOZakupuNekretnine) odk;
            txtIDUgovora.setText(ugovor.getIdUgovoraOZakupu() + "");
            txtMestoSklapanja.setText(ugovor.getMestoSklapanja());
            txtUkupnoZaUplatu.setText(ugovor.getUkupnoZaUplatu() + "");
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(ugovor.getDatumDo());
            cmbDatumDo.setEnabled(true);
            cmbDatumDo.setSelectedDate(gc);
            cmbDatumDo.setEnabled(false);
            gc.setTime(ugovor.getDatumOd());
            cmbDatumOd.setSelectedDate(gc);
            gc.setTime(ugovor.getDatumSklapanja());
            cmbDatumSklapanja.setSelectedDate(gc);
            nekretnina.popuniPolja(ugovor.getNekretnina());
            klijent.popuniPolja(ugovor.getKlijent());

            LocalDate d1 = LocalDate.of(cmbDatumOd.getSelectedDate().get(Calendar.YEAR), cmbDatumOd.getSelectedDate().get(Calendar.MONTH) + 1, cmbDatumOd.getSelectedDate().get(Calendar.DAY_OF_MONTH));
            cmbDatumDo.setEnabled(true);
            LocalDate d2 = LocalDate.of(cmbDatumDo.getSelectedDate().get(Calendar.YEAR), cmbDatumDo.getSelectedDate().get(Calendar.MONTH) + 1, cmbDatumDo.getSelectedDate().get(Calendar.DAY_OF_MONTH));
            cmbDatumDo.setEnabled(false);
            Period diff = Period.between(d1, d2);

            txtBrojMeseci.setText(diff.getMonths() + "");
        }
    }

    @Override
    public OpstaDomenskaKlasa preuzmiPolja() throws Exception {
        if (txtMestoSklapanja.getText().trim().isEmpty() || txtBrojMeseci.getText().trim().isEmpty()) {
            throw new Exception("Morate popuniti sva polja");
        }
        if (!klijent.isVisible()) {
            throw new Exception("Morate izabrati klijenta");
        }
        if (!nekretnina.isVisible()) {
            throw new Exception("Morate izabrati nekretninu");
        }
        NekretninaZaIzdavanje n = (NekretninaZaIzdavanje) nekretnina.preuzmiPolja();
        Klijent k = (Klijent) klijent.preuzmiPolja();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        Date datumOd = java.sql.Date.valueOf(sdf.format(cmbDatumOd.getSelectedDate().getTime()));
        
        if (datumOd.before(c.getTime())) {
            throw new Exception("Datum od ne moze biti pre danasnjeg dana");
        }
        Date datumDo = java.sql.Date.valueOf(sdf.format(cmbDatumDo.getSelectedDate().getTime()));
        Date datumSklapanja = java.sql.Date.valueOf(sdf.format(cmbDatumSklapanja.getSelectedDate().getTime()));
        BigDecimal ukupnoZaUplatu = new BigDecimal(txtUkupnoZaUplatu.getText().trim());
        String mestoSklapanja = txtMestoSklapanja.getText().trim();

        UgovorOZakupuNekretnine ugovor = new UgovorOZakupuNekretnine(null, datumSklapanja, mestoSklapanja, datumOd, datumDo, ukupnoZaUplatu, n, k, Sesija.getInstance().getPrijavljeniAgent());
        return ugovor;
    }

    @Override
    public void isprazniPolja() {
        txtIDUgovora.setText("");
        txtMestoSklapanja.setText("");
        txtUkupnoZaUplatu.setText("");
        txtBrojMeseci.setText("");
    }

    @Override
    public void postaviVidljivostPoljima(boolean signal) {
        txtBrojMeseci.setEditable(signal);
        txtMestoSklapanja.setEditable(signal);
        txtUkupnoZaUplatu.setEditable(signal);
        cmbDatumSklapanja.setEnabled(signal);
        cmbDatumOd.setEnabled(signal);
    }

    @Override
    public void popuniPodatke() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
