/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.klijent;

import kontroler.Kontroler;
import domain.Klijent;
import domain.OpstaDomenskaKlasa;
import domain.UgovorOKupoprodajiNekretnine;
import domain.UgovorOZakupuNekretnine;
import form.FrmDialog;
import form.FrmForma;
import form.IPanel;
import form.PanelModeEnum;
import form.nekretnina.PnlNovaNekretnina;
import form.ugovorProdaja.PnlNoviUgovorOProdajiNekretnine;
import form.ugovorProdaja.model.TableModelUgovoriOKupoprodaji;
import form.ugovorZakup.PnlNoviUgovorOIzdavanjuNekretnine;
import form.ugovorZakup.model.TableModelUgovoriOIzdavanju;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class PnlPrikazKlijenta extends javax.swing.JPanel implements IPanel {

    PnlUnosKlijenta klijent;

    /**
     * Creates new form PnlPrikazKlijenta
     */
    public PnlPrikazKlijenta() {
        initComponents();
        dekorisiPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdaja = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIzdavanje = new javax.swing.JTable();
        pnlKlijent = new javax.swing.JPanel();
        btnOtkazi = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();

        jLabel1.setText("Sklopljeni ugovori o izdavanju nekretnina:");

        tblProdaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdaja);

        jLabel2.setText("Sklopljeni ugovori o prodaji nekretnina:");

        tblIzdavanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIzdavanje);

        pnlKlijent.setLayout(new javax.swing.BoxLayout(pnlKlijent, javax.swing.BoxLayout.Y_AXIS));

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikazi detalje o ugovoru");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlKlijent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrikazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnPrikazi))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int row = tblProdaja.getSelectedRow();
        TableModelUgovoriOKupoprodaji model = (TableModelUgovoriOKupoprodaji) tblProdaja.getModel();
        int row1 = tblIzdavanje.getSelectedRow();
        TableModelUgovoriOIzdavanju model1 = (TableModelUgovoriOIzdavanju) tblIzdavanje.getModel();
        if (row != -1) {
            UgovorOKupoprodajiNekretnine ugovor = model.getUgovori().get(row);
            PnlNoviUgovorOProdajiNekretnine panel = new PnlNoviUgovorOProdajiNekretnine(PanelModeEnum.PRIKAZ);
            panel.popuniPolja(ugovor);

            FrmDialog forma = new FrmDialog((FrmForma) SwingUtilities.getWindowAncestor(this), true, panel);
            forma.setVisible(true);
        } else {

            if (row1 != -1) {
                UgovorOZakupuNekretnine ugovor = model1.getUgovori().get(row);
                PnlNoviUgovorOIzdavanjuNekretnine panel = new PnlNoviUgovorOIzdavanjuNekretnine(PanelModeEnum.PRIKAZ);
                panel.popuniPolja(ugovor);
                panel.postaviVidljivostPoljima(false);
                FrmDialog form = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);

                form.setVisible(true);
            }
        }

        if (row == -1 && row1 == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati ugovor");
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();

    }//GEN-LAST:event_btnOtkaziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlKlijent;
    private javax.swing.JTable tblIzdavanje;
    private javax.swing.JTable tblProdaja;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        klijent.popuniPolja(odk);
        UgovorOKupoprodajiNekretnine ugovor = new UgovorOKupoprodajiNekretnine();
        UgovorOZakupuNekretnine ugovor1 = new UgovorOZakupuNekretnine();
        try {
            ugovor.setKlijent((Klijent) klijent.preuzmiPolja());
            ugovor1.setKlijent((Klijent) klijent.preuzmiPolja());
            List<UgovorOKupoprodajiNekretnine> prodajaUg = Kontroler.getInstance().pretraziUgovoreOKupoprodaji(ugovor);
            List<UgovorOZakupuNekretnine> zakupUg = Kontroler.getInstance().pretraziUgovoreOZakupu(ugovor1);
            TableModelUgovoriOIzdavanju modelI = (TableModelUgovoriOIzdavanju) tblIzdavanje.getModel();
            TableModelUgovoriOKupoprodaji modelP = (TableModelUgovoriOKupoprodaji) tblProdaja.getModel();
            modelI.setUgovori(zakupUg);
            modelP.setUgovori(prodajaUg);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public OpstaDomenskaKlasa preuzmiPolja() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void isprazniPolja() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void dekorisiPanel() {
        Box boxes[] = new Box[1];
        boxes[0] = Box.createHorizontalBox();

        boxes[0].createGlue();

        pnlKlijent.add(boxes[0]);

        klijent = new PnlUnosKlijenta(PanelModeEnum.PRIKAZ);
        klijent.postaviVidljivostPoljima(false);

        klijent.setPreferredSize(new Dimension(850, 190));

        boxes[0].add(klijent);

        TableModelUgovoriOIzdavanju izdavanje = new TableModelUgovoriOIzdavanju(new LinkedList<>());
        tblIzdavanje.setModel(izdavanje);
        TableModelUgovoriOKupoprodaji prodaja = new TableModelUgovoriOKupoprodaji(new LinkedList<>());
        tblProdaja.setModel(prodaja);

    }

    @Override
    public void postaviVidljivostPoljima(boolean signal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void popuniPodatke() {
    }
}
