/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.klijent;

import com.sun.xml.internal.bind.v2.schemagen.episode.Klass;
import kontroler.Kontroler;
import domain.Klijent;
import domain.OpstaDomenskaKlasa;
import form.FrmDialog;
import form.FrmForma;
import form.IPanel;
import form.PanelModeEnum;
import form.ugovorProdaja.model.TableModelUgovoriOKupoprodaji;
import form.ugovorZakup.model.TableModelUgovoriOIzdavanju;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Administrator
 */
public class PnlUnosKlijenta extends javax.swing.JPanel implements IPanel {

    PanelModeEnum mode;

    /**
     * Creates new form PnlUnosKlijenta
     */
    public PnlUnosKlijenta(PanelModeEnum mode) {
        initComponents();
        this.mode = mode;
        dekorisiPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDKlijenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDatumRodjenja = new datechooser.beans.DateChooserCombo();
        txtPrezime = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Unos klijenta"));

        txtIDKlijenta.setEditable(false);

        jLabel1.setText("ID Klijenta:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        cmbDatumRodjenja.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    btnOtkazi.setText("Otkazi");
    btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOtkaziActionPerformed(evt);
        }
    });

    btnIzmeni.setText("Izmeni");
    btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnIzmeniActionPerformed(evt);
        }
    });

    btnSacuvaj.setText("Sacuvaj");
    btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSacuvajActionPerformed(evt);
        }
    });

    btnUnos.setText("Novi unos");
    btnUnos.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUnosActionPerformed(evt);
        }
    });

    jLabel6.setText("JMBG:");

    jLabel7.setText("Datum rodjenja:");

    jLabel8.setText("Broj telefona:");

    jLabel9.setText("Email:");

    jLabel10.setText("Adresa:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel6))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtPrezime)
                .addComponent(txtIme)
                .addComponent(txtIDKlijenta)
                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAdresa)
                        .addComponent(txtEmail)
                        .addComponent(txtBrojTelefona)
                        .addComponent(cmbDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtkazi)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnIzmeni)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnSacuvaj)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnUnos)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUnos)
                                .addComponent(btnSacuvaj)
                                .addComponent(btnIzmeni)
                                .addComponent(btnOtkazi)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtIDKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))))
            .addContainerGap(42, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        if (mode == PanelModeEnum.IZMENA) {
            (((FrmForma) SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
        }
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            Klijent klijent = (Klijent) preuzmiPolja();
            if (mode == PanelModeEnum.IZMENA) {
                klijent = Kontroler.getInstance().izmenaKlijenta(klijent);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili klijenta");
            } else {
                klijent = Kontroler.getInstance().unosKlijenta(klijent);
                JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali klijenta");
            }
            popuniPolja(klijent);
            postaviVidljivostPoljima(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        isprazniPolja();
        postaviVidljivostPoljima(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        postaviVidljivostPoljima(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnUnos;
    private datechooser.beans.DateChooserCombo cmbDatumRodjenja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDKlijenta;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Klijent klijent = (Klijent) odk;

        txtIDKlijenta.setText(klijent.getIdKlijent() + "");
        txtAdresa.setText(klijent.getAdresa());
        txtBrojTelefona.setText(klijent.getBrTelefona());
        txtEmail.setText(klijent.getEmail());
        txtIme.setText(klijent.getIme());
        txtJMBG.setText(klijent.getJmbg());
        txtPrezime.setText(klijent.getPrezime());
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(klijent.getDatumRodjenja());
        cmbDatumRodjenja.setSelectedDate(gc);
    }

    @Override
    public OpstaDomenskaKlasa preuzmiPolja() throws Exception {
        Klijent klijent;
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String adresa = txtAdresa.getText().trim();
        String brojTel = txtBrojTelefona.getText().trim();
        String jmbg = txtJMBG.getText().trim();
        if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || adresa.isEmpty() || brojTel.isEmpty() || jmbg.isEmpty()) {
            throw new Exception("Morate uneti sva polja");
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date datumRodjenja = java.sql.Date.valueOf(sdf.format(cmbDatumRodjenja.getSelectedDate().getTime()));
        if (mode == PanelModeEnum.PRIKAZ) {
            klijent = new Klijent(new Long(txtIDKlijenta.getText().trim()), ime, prezime, jmbg, datumRodjenja, brojTel, email, adresa);
        } else {
            if (!email.contains("@")) {
                throw new Exception("Email mora da sadrzi znak '@'");
            }
            if (jmbg.length() != 13) {
                throw new Exception("JMBG mora da ima 13 cifara");
            }
            Calendar c = Calendar.getInstance();
            c.set(c.get(Calendar.YEAR) - 18, c.get(Calendar.MONTH), c.get(Calendar.DAY_OF_MONTH));
            if (datumRodjenja.after(c.getTime())) {
                throw new Exception("Klijent mora biti stariji od 18 godina");
            }
            if (mode == PanelModeEnum.UNOS) {
                klijent = new Klijent(null, ime, prezime, jmbg, datumRodjenja, brojTel, email, adresa);
            } else {
                klijent = new Klijent(new Long(txtIDKlijenta.getText().trim()), ime, prezime, jmbg, datumRodjenja, brojTel, email, adresa);
            }
        }
        return klijent;
    }

    @Override
    public void isprazniPolja() {
        txtAdresa.setText("");
        txtBrojTelefona.setText("");
        txtEmail.setText("");
        txtIDKlijenta.setText("");
        txtIme.setText("");
        txtJMBG.setText("");
        txtPrezime.setText("");
    }

    @Override
    public void dekorisiPanel() {
        if (mode == PanelModeEnum.IZMENA) {
            btnUnos.setVisible(false);
            btnIzmeni.setVisible(true);
            setBorder(new TitledBorder("Izmena klijenta"));
        } else if (mode == PanelModeEnum.UNOS) {
            btnUnos.setVisible(true);
            btnIzmeni.setVisible(false);
            setBorder(new TitledBorder("Unos klijenta"));
        } else if (mode == PanelModeEnum.PRIKAZ) {
            btnIzmeni.setVisible(false);
            btnOtkazi.setVisible(false);
            btnSacuvaj.setVisible(false);
            btnUnos.setVisible(false);
            setBorder(new TitledBorder("Klijent"));
            postaviVidljivostPoljima(false);
        }
    }

    @Override
    public void postaviVidljivostPoljima(boolean signal) {
        txtIme.setEditable(signal);
        txtAdresa.setEditable(signal);
        txtBrojTelefona.setEditable(signal);
        txtEmail.setEditable(signal);
        txtJMBG.setEditable(signal);
        txtPrezime.setEditable(signal);
        cmbDatumRodjenja.setEnabled(signal);

        btnSacuvaj.setEnabled(signal);
    }

    @Override
    public void popuniPodatke() {
    }

    public void postaviModele() {
    }
}
